### ISSUE TITLE
chjj: Why remove ASICBoost protection, create an issue on ASICBoost, then add the protection back nearly the same day?

### ISSUE THREAD

**Issue by BIPBIPBIPBIP** [tothemoon-org/extension-blocks#12]
In your commit on Apr 4, 2017:
https://github.com/tothemoon-org/extension-blocks/commit/5f42712a5ae56f4b27451184aa516001bcae3784

You removed this line from the spec:
> -**Regular txids**, although not necessary for security purposes, **are included** for the possibility of regular TXID merkle proofs.

This part makes reordering of tx changes the coinbase, thus makes changing the right side of the merkle tree, also changes the left side.

That line was all you need to prevent ASICBoost from having an advantage.

So, why did you remove that, then bury it under a bunch of commits in the same day?

Even the commit has a bunch of edits above and below it, just by looking at the commit title:
> spec: add history. clarification on tx cost. 

People would have no idea you actually removed the ASICBoost protection.

And why then did you create a PR asking for help to deal with ASICBoost the next day?
> [chjj opened this Issue Apr 5, 2017: Add extra commitment to prevent asicboost?](https://github.com/tothemoon-org/extension-blocks/issues/6)

And then you quickly accepted a PR just to add a similar line (that you deleted a day ago) back into the spec again: (https://github.com/tothemoon-org/extension-blocks/pull/7/commits/5331eeed1880ecc43a250313415e0d0b02c56bab )
> -The merkle root is to be calculated as a merkle tree with all extension block txids and wtxids as the leaves.
>+The merkle root is to be calculated as a merkle tree with all extension **and canonical** block txids and wtxids as the leaves.

All these look too scripted don't you think?

It's like you went out of your way just to make ASICBoost a big deal when Extension Block was already protected from it due to commitment structure being based on BIP-141 SegWit, all the regular tx and extension tx were already included in the coinbase merkle root.

And all this happened at the same time Greg Maxwell posted his ASICBoost inhibiting proposal.
 
Is someone in bed with Blockstream or what?

Did you think no one was watching?

**Comment by chjj** [comment]
> You removed this line from the spec:

That line was referring to regular TXIDs within the extension block, which were mentioned the line before it as well. If you look at the commit history, it used to only include WTXIDs within the ext. block. We modified it to include the regular TXIDs in the ext. block as well (but not regular TXIDs within the canonical block since we weren't aware of asicboost at the time).

The line you're referring to was removed because it was extra cruft. Removing it changed absolutely nothing about the merkle construction. These political attacks don't belong here. Closing.
